[package]
name = "matcher-cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "matcher"
path = "src/matcher.rs"

[[bin]]
name = "matcher"
path = "src/main.rs"

[dependencies]
criterion = "0.5"
strum = { version = "0.26", features = ["derive"] }
priority-queue = "1.3.2"
uuid = { version = "1.6", features = ["serde", "v4"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
